export default {
  READ_QUESTIONS: "READ_QUESTIONS",
  CREATE_QUESTION: "CREATE_QUESTION",
  SORT_QUESTIONS: "SORT_QUESTIONS",
  SET_QUESTIONS: "SET_QUESTIONS",
  DELETE_QUESTION: "DELETE_QUESTION",
  UPDATE_QUESTION: "UPDATE_QUESTION"
};
